FROM lezsakdomi/capnproto-cplusplus:buster-buildpack

ARG MAKEFLAGS=""
ARG BUILD_TARGET=""
ARG WORKDIR="/src"

COPY . $WORKDIR
WORKDIR $WORKDIR

ARG BUILD_ARGS=""
RUN make $BUILD_TARGET $BUILD_ARGS -$MAKEFLAGS

ARG RUN_ARGS="RUN_REDIRECTS='2>/dev/null'"
ENTRYPOINT make run $RUN_ARGS -$MAKEFLAGS
